### ISSUE TITLE
dnf 2016 with virtualbox provisioner

### ISSUE THREAD

**Issue by dkalog** [lowescott/learning-tools#103] opened 2017-11-19 15:58 UTC
Hi 
I am trying to modify the Vagrant file  of  dnf-2016 for VirtualBox provider but I stumble across the 
metadata of https://app.vagrantup.com/slowe/boxes/ubuntu-trusty-x64 which applies only for the vmware case. How can I overcome this ?

**Comment by lowescott** [comment] 2017-11-20 17:52
Hi @dkalog, can you clarify the environment/repository to which you are referring? It sounds like you're talking about the 2016 DNF materials repository (https://github.com/lowescott/2016-dnf-materials), but you opened the issue in this repository. Can you point me in the right direction so I can try to reproduce the issue?

**Comment by lowescott** [comment] 2018-01-23 18:13
I'm closing this issue due to lack of additional information. Please feel free to re-open it if anyone has additional questions or needs more information.

**Closed by lowescott** 2018-01-23 18:13 UTC
